### ISSUE TITLE
[Feature] 채팅 기능

### ISSUE THREAD

**Issue by Kongji82** [kakaotech-bootcamp-11/ktb-11-project-1-chatbot-fe#3]
### Description
- 채팅방 내역에서 한 쓰레드 클릭 시, 해당 채팅방 ID로 채팅들 불러오는 API fetch 및 배치

### TODO

- [ ] 채팅방 내역 API 가져오기
  - [x] API 호출
  - [x] 화면에 표시
- [ ] 채팅 기록 호출
  - [ ] 채팅 기록 API 호출
  - [ ] 채팅 내역 화면에 표시
